_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": pred.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": pred._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw.captions
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": pred.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": pred.captions
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt.captions
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": pred.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ssim
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": pred.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": pred.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gt.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": psnr
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": raw.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.13
            "5": 0.19.1
            "6": 4.37.2
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
hparams:
    value: Namespace(model_name='UIEC2Net', crop_size=256, input_norm=False, epochs=1, batch_size=16, num_workers=4, initlr=0.001, weight_decay=0.0, lr_config='CyclicLR')
