_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.13
            "5": 0.19.1
            "6": 4.37.2
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
hparams:
    value: Namespace(model_name='UIEC2Net', crop_size=256, input_norm=False, epochs=100, batch_size=8, num_workers=4, initlr=0.001, weight_decay=0.0, lr_config='CyclicLR')
